CREATE DATABASE LIVRARIA
USE LIVRARIA

 

CREATE TABLE CATEGORIA (
COD_CATEGORIA INT NOT NULL,
DESCRIÇÃO VARCHAR(60),
CONSTRAINT PKCOD PRIMARY KEY (COD_CATEGORIA))

 

CREATE TABLE LIVRO ( 
COD_LIVRO INT NOT NULL,
TITULO VARCHAR(30), 
ANO CHAR(4),
COD_CATEGORIA INT NOT NULL,
CONSTRAINT PKCO PRIMARY KEY(COD_LIVRO),
CONSTRAINT FKCOD FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA))

 

CREATE TABLE AUTOR( 
COD_AUTOR INT NOT NULL, 
NOME VARCHAR(30),
DT_NASCIMENTO DATE,
BIOGRAFIA VARCHAR(200),
NACIONALIDADE VARCHAR(20),
CONSTRAINT PKCODD PRIMARY KEY(COD_AUTOR))

 

 

CREATE TABLE LIVRO_AUTOR(
COD_LIVRO INT NOT NULL,
COD_AUTOR INT NOT NULL, 
CONSTRAINT FKCO FOREIGN KEY (COD_LIVRO) REFERENCES LIVRO,
CONSTRAINT FKCODD FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR )